# Generated by Django 3.2.15 on 2023-08-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coords', '0002_auto_20230824_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
