# Generated by Django 3.2.15 on 2023-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_add_price_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UN', 'Необработанный'), ('RS', 'Передан в ресторан'), ('DL', 'Доставляется'), ('OK', 'Выполнен')], db_index=True, default='UN', max_length=2, verbose_name='статус'),
        ),
    ]
