# Generated by Django 3.2.15 on 2023-08-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(to='foodcartapp.Restaurant', verbose_name='рестораны'),
        ),
    ]
