# Generated by Django 3.2.15 on 2023-08-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='готовит ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(to='foodcartapp.Restaurant', verbose_name='рестораны, которые могут приготовить'),
        ),
    ]
