# Generated by Django 3.2.15 on 2023-08-07 17:37

from django.db import migrations


def copy_price_to_orderproducts(apps, schema_editor):
    Product = apps.get_model('foodcartapp', 'Product')
    OrderProducts = apps.get_model('foodcartapp', 'OrderProducts')
    products = Product.objects.all()
    for product in products.iterator():
        orders_with_product = product.order.all()
        for order in orders_with_product:
            order.price = product.price
        OrderProducts.objects.bulk_update(orders_with_product, ['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderproducts_price'),
    ]

    operations = [
        migrations.RunPython(copy_price_to_orderproducts)
    ]
