# Generated by Django 3.2.15 on 2023-08-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230816_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличными'), ('TF', 'Переводом')], db_index=True, default='CH', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
